#!/bin/bash
set -euo pipefail

vm_name="${1:-$(basename "$0")}"

until command -v multipass > /dev/null
do
  echo "Multipass is not installed, do you wish to install it?"
  select install in "Yes" "No"; do
    case $install in
        Yes ) sudo snap install multipass; break;;
	No ) break;;
    esac
  done
done

if ! multipass start "${vm_name}"
then
  set -x
  multipass launch -v -n "${vm_name}" --cloud-init - hirsute <<EOF
apt:
  preserve_sources_list: true
  sources:
      mir-team:
          source: 'ppa:mir-team/release'
ssh_authorized_keys:
    - $(cat ~/.ssh/id_rsa.pub)
packages:
    - xwayland
    - fonts-freefont-ttf
    - xfce4-terminal
    - xfce4-goodies
    - epiphany-browser
runcmd:
    - sudo snap install --classic --edge egmde
EOF
  multipass exec "${vm_name}" -- sh -c "mkdir --parents ~/.config"
  multipass exec "${vm_name}" -- sh -c "echo enable-key-repeat=false >> .config/egmde.config"
  multipass exec "${vm_name}" -- sh -c "echo enable-autostart=  >> .config/egmde.config"
  keymap_index=$(gsettings get org.gnome.desktop.input-sources current | cut -d\  -f 2)
  keymap=$(gsettings get org.gnome.desktop.input-sources sources | grep -Po "'[[:alpha:]]+'\)" | sed -ne "s/['|)]//g;$((keymap_index+1))p")
  if [ -n "${keymap}" ]; then
    multipass exec "${vm_name}" -- sh -c "echo keymap=${keymap}  >> .config/egmde.config"
  fi
  set +x
fi

host_ip=$(multipass info "${vm_name}" --format csv | awk -F, '/^'"${vm_name}"'/ { print $3 }')

ssh -X "ubuntu@${host_ip}" sh -lc egmde
