#!/bin/bash
set -euo pipefail

vm_name="${1:-mir-demos}"

until command -v multipass > /dev/null
do
  echo "Multipass is not installed, do you wish to install it?"
  select install in "Yes" "No"; do
    case $install in
        Yes ) sudo snap install multipass; break;;
	No ) break;;
    esac
  done
done

if ! multipass start "${vm_name}"
then
  set -x
  multipass launch -v -n "${vm_name}" --cloud-init - <<EOF
apt:
  preserve_sources_list: true
  sources:
      mir-team:
          source: 'ppa:mir-team/release'
ssh_authorized_keys:
    - $(cat ~/.ssh/id_rsa.pub)
packages:
    - xwayland
    - fonts-freefont-ttf
    - fonts-font-awesome
    - xfce4-terminal
    - epiphany-browser
    - mir-graphics-drivers-desktop
    - mir-demos
    - mir-test-tools
runcmd:
    - sudo snap install --classic --edge egmde
    - sudo snap install mircade
    - sudo snap install --edge egmde-confined-desktop
EOF
  multipass exec "${vm_name}" -- mircade --help > /dev/null || true
  multipass exec "${vm_name}" -- egmde-confined-desktop --help > /dev/null || true
  multipass exec "${vm_name}" -- sh -c "mkdir --parents ~/.config"
  multipass exec "${vm_name}" -- sh -c "if ! grep -q no-of-workspaces= ~/.config/egmde.config; then echo no-of-workspaces=4 >> .config/egmde.config; fi"
  multipass exec "${vm_name}" -- sh -c "if ! grep -q enable-autostart= ~/.config/egmde.config; then echo enable-autostart=  >> .config/egmde.config; fi"
  set +x
fi

host_ip=$(multipass info "${vm_name}" --format csv | awk -F, '/^'"${vm_name}"'/ { print $3 }')

while :
do
  echo "Choose the Mir server you'd like to try (\"0\" to exit):"
  select demo in "egmde"\
	         "miral-app"\
		 "miral-app -kiosk"\
		 "miral-app -demo-server"\
                 "miral-app --window-manager tiling"\
                 "cp --force .Xauthority snap/mircade/current/&&mircade"\
                 "cp --force .Xauthority snap/egmde-confined-desktop/current/&&egmde-confined-desktop"
  do
    if [ "$demo" = "" ]; then exit 0; fi
    ssh -X "ubuntu@${host_ip}" sh -lc "\"$demo\""
    break
  done
done
